# This file contains the model's configurations

language: "el" 

pipeline:
  - name: SpacyNLP
    model: "el_core_news_md"
  - name: SpacyTokenizer
  - name: LexicalSyntacticFeaturizer
    "features": [
      ["low","upper"], # features from token before current one
      ["low","upper","title", "BOS", "EOS",], # features from current token
      ["low","upper"], # features from token after the current one
    ]
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 30

policies:
 - name: TEDPolicy
   max_history: 5
   epochs: 50
 - name: RulePolicy